// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeCareHistory.Models;

namespace ShoeCareHistory.Migrations
{
    [DbContext(typeof(ShoeCareHistoryContext))]
    [Migration("20181019105504_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoeCareHistory.Models.CareBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CareBrand");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.CareItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CareBrandId");

                    b.Property<int>("CareCategory");

                    b.Property<int?>("HistoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CareBrandId");

                    b.HasIndex("HistoryId");

                    b.ToTable("CareItem");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CareDate");

                    b.Property<string>("Detail");

                    b.Property<int?>("ShoeId");

                    b.HasKey("Id");

                    b.HasIndex("ShoeId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Color");

                    b.Property<string>("Leather");

                    b.Property<string>("Name");

                    b.Property<string>("ProductName");

                    b.Property<DateTime>("ProductionDate");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int?>("ShoeMakerId");

                    b.HasKey("Id");

                    b.HasIndex("ShoeMakerId");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.ShoeMaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<int>("Established");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ShoeMaker");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.CareItem", b =>
                {
                    b.HasOne("ShoeCareHistory.Models.CareBrand", "CareBrand")
                        .WithMany()
                        .HasForeignKey("CareBrandId");

                    b.HasOne("ShoeCareHistory.Models.History")
                        .WithMany("CareItems")
                        .HasForeignKey("HistoryId");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.History", b =>
                {
                    b.HasOne("ShoeCareHistory.Models.Shoe", "Shoe")
                        .WithMany()
                        .HasForeignKey("ShoeId");
                });

            modelBuilder.Entity("ShoeCareHistory.Models.Shoe", b =>
                {
                    b.HasOne("ShoeCareHistory.Models.ShoeMaker", "ShoeMaker")
                        .WithMany()
                        .HasForeignKey("ShoeMakerId");
                });
#pragma warning restore 612, 618
        }
    }
}
